[package]
name = "rusty-maid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.12.0", features = ["macros", "auto-send"] }
tokio = { version = "1.20.0", features = ["full"] }
dotenv = "0.15.0"
anyhow = "1.0.58"
reqwest = { version = "0.11.11", optional = true }
chrono = "0.4.23"
async-trait = "0.1.56"
rand = "0.8.5"
lazy_static = "1.4.0"
tracing = "0.1.35"
tracing-subscriber = "0.3.15"
scraper = "0.15.0"
regex = "1.6.0"
paste = "1.0.7"
deepl = "0.4.1"
typed-builder = "0.14.0"
make-quote = "0.2.2"
tempfile = "3.5.0"

# osu
rosu-v2 = "0.7.0"
rosu-pp = "0.9.4"

# Cache Management
r2d2 = "0.8.10"
redis = { version = "0.22.2", features = ["r2d2"] }

serde = { version = "1.0.138", features = ["derive"]}
serde_json = "1.0.82"
toml = "0.7.3"

[[bin]]
name = "tgbot"

[profile.release]
debug = 0
strip = "symbols"
lto = true
opt-level = 3

[features]
default = ["reqwest", "osu"]
osu = []
reqwest = ["dep:reqwest"]
