version: 3

networks:
  rusty-maid-network:
    external: false

service:
  bot:
    image: 'ghcr.io/avimitin/tg-maid:latest'
    restart: always
    container_name: rusty-maid
    networks:
      - rusty-maid-network
    depends_on:
      - cache
    volumes:
      - "./app:/app"

  cache:
    image: 'redis:latest'
    networks:
      - rusty-maid-network
    container_name: rusty-maid-cache
    volumes:
      - "./redis-data:/data"
