name: Build Docker Image

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'example*'
      - 'readme.md'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: nix-shell -p nix-info --run "nix-info -m"
      - name: Build & Push
        env:
          LATEST_IMAGE: 'true'
          PUSH_IMAGE: 'true'
        run: nix run .#tg-maid.docker-image.finalizer
