name: Build Docker Image

on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Fetch assets
        run: |
          mkdir -p /home/runner/work/fonts/
          curl -fLo /home/runner/work/fonts/quote-test-font.ttc https://github.com/notofonts/noto-cjk/raw/main/Sans/OTC/NotoSansCJK-Black.ttc
          curl -fLo /home/runner/work/fonts/quote-username-font.ttc https://github.com/notofonts/noto-cjk/raw/main/Sans/OTC/NotoSansCJK-Light.ttc
      - name: Build The bot
        env:
          QUOTE_TEXT_FONT_PATH: /home/runner/work/fonts/quote-test-font.ttc
          QUOTE_USERNAME_FONT_PATH: /home/runner/work/fonts/quote-username-font.ttc
        run: cargo build --release
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/avimitin/tg-maid:latest
